### ISSUE TITLE
Cancelling a job

### ISSUE THREAD

**Issue by bpmweel** [NLeSC/compute-service-api#1]
We discussed what the best way was to cancel a job. I found [this stackoverflow question](http://stackoverflow.com/questions/17529315/hateoas-how-to-model-link-relations-that-change-state) which provides a number of solutions.

It mentions a new verb for http called PATCH which may be a fit, what do you guys think?

**Comment by LourensVeen** [comment]
I like cayuu's solution in that thread better than my original idea of reifying the runner and then deleting it: make the status a subresource that you can then PUT to. It's closer to intuitive for most people I think.

PATCH would be an alternative for that where the status is part of the job, but then the question arises what else you can patch, and it's not as well known I think (but maybe that's just because I'd never heard of it :-)). Also maybe canceling the job would cause other parts of it to change, so that you end up with a current state, a patch, and a new state which isn't simply the current state plus the changes in the patch.

**Comment by sverhoeven** [comment]
We choose `POST to /jobs/{jobId}/cancel` for now
